repos:
  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        args: [--check]
        files: ^.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
        args: [--check]
        files: ^.*\.py$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        files: ^.*\.py$


  - repo: local
    hooks:
    -   id: launch_tests
        name: Unit tests
        entry: ./launch_tests.sh
        pass_filenames: false
        language: script
